### ISSUE TITLE
Quick Switch shortcut not working in 2.9.8

### ISSUE THREAD

**Issue by geoffcallender** [anjlab/eclipse-tapestry5-plugin#24]
This problem existed in 2.9.7 and there was a fix for it in 2.9.8. However, the problem is still there for me, but the messages in the Error log are a bit different (see below). I did the upgrade from 2.9.7 via Help > Check for Updates, followed by a restart of Eclipse. The shortcut didn't work so I closed all the editors, opened one for a .tml file and started testing the Quick Switch. No luck.

Message:
Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".

Exception Stack Trace:
java.lang.NullPointerException
	at com.anjlab.eclipse.tapestry5.views.context.TapestryContextView$2.contextChanged(TapestryContextView.java:86)
	at com.anjlab.eclipse.tapestry5.watchdog.TapestryContextWatchdog.notifyContextChanged(TapestryContextWatchdog.java:43)
	at com.anjlab.eclipse.tapestry5.watchdog.TapestryContextWatchdog.changeContext(TapestryContextWatchdog.java:61)
	at com.anjlab.eclipse.tapestry5.watchdog.TapestryContextWatchdog.access$1(TapestryContextWatchdog.java:55)
	at com.anjlab.eclipse.tapestry5.watchdog.TapestryContextWatchdog$1.resourceChanged(TapestryContextWatchdog.java:103)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:291)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:285)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:149)
	at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:378)
	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1498)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:156)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

Session Data:
eclipse.buildId=4.4.2.M20150204-1700
java.version=1.7.0_71
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product -keyring /Users/geocal/.eclipse_keyring -showlocation
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.jee.product -keyring /Users/geocal/.eclipse_keyring -showlocation

Each time I try the shortcut afterwards I get this...

Message:
This feature is not available for your Eclipse runtime

Exception Stack Trace:
An exception stack trace is not available.

**Comment by dmitrygusev** [comment]
@geoffcallender could you please try version 2.9.9 I just published?

**Comment by geoffcallender** [comment]
Sorry, no good! 

Message:
This feature is not available for your Eclipse runtime

Exception Stack Trace:
An exception stack trace is not available.


This might have been straight after the upgrade to 2.9.9, or it might have been before (but I doubt it)...

Message:
Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".

Exception Stack Trace:
java.lang.NullPointerException
	at com.anjlab.eclipse.tapestry5.views.context.TapestryContextView$2.contextChanged(TapestryContextView.java:86)
	at com.anjlab.eclipse.tapestry5.watchdog.TapestryContextWatchdog.notifyContextChanged(TapestryContextWatchdog.java:43)
	at com.anjlab.eclipse.tapestry5.watchdog.TapestryContextWatchdog.changeContext(TapestryContextWatchdog.java:61)
	at com.anjlab.eclipse.tapestry5.watchdog.TapestryContextWatchdog.access$1(TapestryContextWatchdog.java:55)
	at com.anjlab.eclipse.tapestry5.watchdog.TapestryContextWatchdog$1.resourceChanged(TapestryContextWatchdog.java:103)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:291)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:285)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:149)
	at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:378)
	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1498)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:156)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

**Comment by dmitrygusev** [comment]
Looks like you haven't upgraded or haven't restarted the Eclipse maybe?
Otherwise I don't understand something.

Stack trace says that the error is on [line 86](https://github.com/anjlab/eclipse-tapestry5-plugin/blob/f8985940781f747a864a5ecb9d69d52e7436db13/com.anjlab.eclipse.tapestry5/src/com/anjlab/eclipse/tapestry5/views/context/TapestryContextView.java#L86):

![2015-03-05 17 26 07](https://cloud.githubusercontent.com/assets/76579/6506524/d55437a2-c35c-11e4-8e24-bda4b971e21c.png)

Which may only happen if `window` is null, but line 81 above ensures that null value can't be here.

**Comment by geoffcallender** [comment]
Just closed all editors, restarted Eclipse, checked installation details to confirm I'm running 2.9.9, and tested. Same message: "This feature is not available for your Eclipse runtime" plug-in: com.anjlab.eclipse.tapestry5. I changed the key binding from Cmd+R to Ctrl+R and retried. Got same message in Error Log.

**Comment by dmitrygusev** [comment]
Geoff,

that last the error was due to changes in internal API made in recent Luna 4.4.2.

I was able to reproduce this after updating my Eclipse, should be fixed in 2.10.0

**Comment by geoffcallender** [comment]
Hi Dmitry,

That worked. Thank you very much. it's great to have that feature back.

Cheers,

Geoff
